/* 
 * Upcloud api
 *
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing IPAddressApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class IPAddressApiTests
    {
        private IPAddressApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new IPAddressApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IPAddressApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' IPAddressApi
            //Assert.IsInstanceOfType(typeof(IPAddressApi), instance, "instance is a IPAddressApi");
        }

        
        /// <summary>
        /// Test IpAddressGet
        /// </summary>
        [Test]
        public void IpAddressGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.IpAddressGet();
            //Assert.IsInstanceOf<InlineResponse2006> (response, "response is InlineResponse2006");
        }
        
        /// <summary>
        /// Test IpAddressIpDelete
        /// </summary>
        [Test]
        public void IpAddressIpDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string ip = null;
            //instance.IpAddressIpDelete(ip);
            
        }
        
        /// <summary>
        /// Test IpAddressIpGet
        /// </summary>
        [Test]
        public void IpAddressIpGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string ip = null;
            //var response = instance.IpAddressIpGet(ip);
            //Assert.IsInstanceOf<InlineResponse2011> (response, "response is InlineResponse2011");
        }
        
        /// <summary>
        /// Test IpAddressIpPut
        /// </summary>
        [Test]
        public void IpAddressIpPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string ip = null;
            //IpAddress1 ipAddress = null;
            //var response = instance.IpAddressIpPut(ip, ipAddress);
            //Assert.IsInstanceOf<InlineResponse2011> (response, "response is InlineResponse2011");
        }
        
        /// <summary>
        /// Test IpAddressPost
        /// </summary>
        [Test]
        public void IpAddressPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //IpAddress ipAddress = null;
            //var response = instance.IpAddressPost(ipAddress);
            //Assert.IsInstanceOf<InlineResponse2011> (response, "response is InlineResponse2011");
        }
        
    }

}
