/* 
 * Upcloud api
 *
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TagApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class TagApiTests
    {
        private TagApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TagApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TagApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TagApi
            //Assert.IsInstanceOfType(typeof(TagApi), instance, "instance is a TagApi");
        }

        
        /// <summary>
        /// Test ServerServerIdTagTagListPost
        /// </summary>
        [Test]
        public void ServerServerIdTagTagListPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? serverId = null;
            //string tagList = null;
            //var response = instance.ServerServerIdTagTagListPost(serverId, tagList);
            //Assert.IsInstanceOf<ServerListResponse> (response, "response is ServerListResponse");
        }
        
        /// <summary>
        /// Test ServerServerIdUntagTagNamePost
        /// </summary>
        [Test]
        public void ServerServerIdUntagTagNamePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? serverId = null;
            //string tagName = null;
            //var response = instance.ServerServerIdUntagTagNamePost(serverId, tagName);
            //Assert.IsInstanceOf<ServerListResponse> (response, "response is ServerListResponse");
        }
        
        /// <summary>
        /// Test TagGet
        /// </summary>
        [Test]
        public void TagGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.TagGet();
            //Assert.IsInstanceOf<InlineResponse2009> (response, "response is InlineResponse2009");
        }
        
        /// <summary>
        /// Test TagPost
        /// </summary>
        [Test]
        public void TagPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Tag tag = null;
            //var response = instance.TagPost(tag);
            //Assert.IsInstanceOf<InlineResponse20010> (response, "response is InlineResponse20010");
        }
        
        /// <summary>
        /// Test TagTagNameDelete
        /// </summary>
        [Test]
        public void TagTagNameDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tagName = null;
            //instance.TagTagNameDelete(tagName);
            
        }
        
        /// <summary>
        /// Test TagTagNamePut
        /// </summary>
        [Test]
        public void TagTagNamePutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tagName = null;
            //Tag1 tag = null;
            //var response = instance.TagTagNamePut(tagName, tag);
            //Assert.IsInstanceOf<InlineResponse20010> (response, "response is InlineResponse20010");
        }
        
    }

}
