/* 
 * Upcloud api
 *
 * Upcloud api specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines ErrorStatus
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ErrorStatus
    {
        
        /// <summary>
        /// Enum _400 for "400"
        /// </summary>
        [EnumMember(Value = "400")]
        _400,
        
        /// <summary>
        /// Enum _402 for "402"
        /// </summary>
        [EnumMember(Value = "402")]
        _402,
        
        /// <summary>
        /// Enum _403 for "403"
        /// </summary>
        [EnumMember(Value = "403")]
        _403,
        
        /// <summary>
        /// Enum _404 for "404"
        /// </summary>
        [EnumMember(Value = "404")]
        _404,
        
        /// <summary>
        /// Enum _409 for "409"
        /// </summary>
        [EnumMember(Value = "409")]
        _409
    }

}
