/* 
 * Upcloud api
 *
 * Upcloud api specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ErrorCode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ErrorCodeTests
    {
        // TODO uncomment below to declare an instance variable for ErrorCode
        //private ErrorCode instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ErrorCode
            //instance = new ErrorCode();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ErrorCode
        /// </summary>
        [Test]
        public void ErrorCodeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ErrorCode
            //Assert.IsInstanceOfType<ErrorCode> (instance, "variable 'instance' is a ErrorCode");
        }


    }

}
