/* 
 * Upcloud api
 *
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2004ServerSizes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2004ServerSizesTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2004ServerSizes
        //private InlineResponse2004ServerSizes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2004ServerSizes
            //instance = new InlineResponse2004ServerSizes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2004ServerSizes
        /// </summary>
        [Test]
        public void InlineResponse2004ServerSizesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2004ServerSizes
            //Assert.IsInstanceOfType<InlineResponse2004ServerSizes> (instance, "variable 'instance' is a InlineResponse2004ServerSizes");
        }

        /// <summary>
        /// Test the property 'ServerSize'
        /// </summary>
        [Test]
        public void ServerSizeTest()
        {
            // TODO unit test for the property 'ServerSize'
        }

    }

}
