/* 
 * Upcloud api
 *
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PriceZone
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PriceZoneTests
    {
        // TODO uncomment below to declare an instance variable for PriceZone
        //private PriceZone instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PriceZone
            //instance = new PriceZone();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PriceZone
        /// </summary>
        [Test]
        public void PriceZoneInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PriceZone
            //Assert.IsInstanceOfType<PriceZone> (instance, "variable 'instance' is a PriceZone");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Firewall'
        /// </summary>
        [Test]
        public void FirewallTest()
        {
            // TODO unit test for the property 'Firewall'
        }
        /// <summary>
        /// Test the property 'IoRequestBackup'
        /// </summary>
        [Test]
        public void IoRequestBackupTest()
        {
            // TODO unit test for the property 'IoRequestBackup'
        }
        /// <summary>
        /// Test the property 'IoRequestHdd'
        /// </summary>
        [Test]
        public void IoRequestHddTest()
        {
            // TODO unit test for the property 'IoRequestHdd'
        }
        /// <summary>
        /// Test the property 'IoRequestMaxiops'
        /// </summary>
        [Test]
        public void IoRequestMaxiopsTest()
        {
            // TODO unit test for the property 'IoRequestMaxiops'
        }
        /// <summary>
        /// Test the property 'Ipv4Address'
        /// </summary>
        [Test]
        public void Ipv4AddressTest()
        {
            // TODO unit test for the property 'Ipv4Address'
        }
        /// <summary>
        /// Test the property 'Ipv6Address'
        /// </summary>
        [Test]
        public void Ipv6AddressTest()
        {
            // TODO unit test for the property 'Ipv6Address'
        }
        /// <summary>
        /// Test the property 'PublicIpv4BandwidthIn'
        /// </summary>
        [Test]
        public void PublicIpv4BandwidthInTest()
        {
            // TODO unit test for the property 'PublicIpv4BandwidthIn'
        }
        /// <summary>
        /// Test the property 'PublicIpv4BandwidthOut'
        /// </summary>
        [Test]
        public void PublicIpv4BandwidthOutTest()
        {
            // TODO unit test for the property 'PublicIpv4BandwidthOut'
        }
        /// <summary>
        /// Test the property 'PublicIpv6BandwidthIn'
        /// </summary>
        [Test]
        public void PublicIpv6BandwidthInTest()
        {
            // TODO unit test for the property 'PublicIpv6BandwidthIn'
        }
        /// <summary>
        /// Test the property 'PublicIpv6BandwidthOut'
        /// </summary>
        [Test]
        public void PublicIpv6BandwidthOutTest()
        {
            // TODO unit test for the property 'PublicIpv6BandwidthOut'
        }
        /// <summary>
        /// Test the property 'ServerCore'
        /// </summary>
        [Test]
        public void ServerCoreTest()
        {
            // TODO unit test for the property 'ServerCore'
        }
        /// <summary>
        /// Test the property 'ServerMemory'
        /// </summary>
        [Test]
        public void ServerMemoryTest()
        {
            // TODO unit test for the property 'ServerMemory'
        }
        /// <summary>
        /// Test the property 'StorageBackup'
        /// </summary>
        [Test]
        public void StorageBackupTest()
        {
            // TODO unit test for the property 'StorageBackup'
        }
        /// <summary>
        /// Test the property 'StorageHdd'
        /// </summary>
        [Test]
        public void StorageHddTest()
        {
            // TODO unit test for the property 'StorageHdd'
        }
        /// <summary>
        /// Test the property 'StorageMaxiops'
        /// </summary>
        [Test]
        public void StorageMaxiopsTest()
        {
            // TODO unit test for the property 'StorageMaxiops'
        }
        /// <summary>
        /// Test the property 'ServerPlan1xCPU1GB'
        /// </summary>
        [Test]
        public void ServerPlan1xCPU1GBTest()
        {
            // TODO unit test for the property 'ServerPlan1xCPU1GB'
        }
        /// <summary>
        /// Test the property 'ServerPlan2xCPU2GB'
        /// </summary>
        [Test]
        public void ServerPlan2xCPU2GBTest()
        {
            // TODO unit test for the property 'ServerPlan2xCPU2GB'
        }

    }

}
