/* 
 * Upcloud api
 *
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RestartServer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RestartServerTests
    {
        // TODO uncomment below to declare an instance variable for RestartServer
        //private RestartServer instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RestartServer
            //instance = new RestartServer();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RestartServer
        /// </summary>
        [Test]
        public void RestartServerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RestartServer
            //Assert.IsInstanceOfType<RestartServer> (instance, "variable 'instance' is a RestartServer");
        }

        /// <summary>
        /// Test the property 'StopType'
        /// </summary>
        [Test]
        public void StopTypeTest()
        {
            // TODO unit test for the property 'StopType'
        }
        /// <summary>
        /// Test the property 'Timeout'
        /// </summary>
        [Test]
        public void TimeoutTest()
        {
            // TODO unit test for the property 'Timeout'
        }
        /// <summary>
        /// Test the property 'TimeoutAction'
        /// </summary>
        [Test]
        public void TimeoutActionTest()
        {
            // TODO unit test for the property 'TimeoutAction'
        }

    }

}
