/* 
 * Upcloud api
 *
 * Upcloud api specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Storage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StorageTests
    {
        // TODO uncomment below to declare an instance variable for Storage
        //private Storage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Storage
            //instance = new Storage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Storage
        /// </summary>
        [Test]
        public void StorageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Storage
            //Assert.IsInstanceOfType<Storage> (instance, "variable 'instance' is a Storage");
        }

        /// <summary>
        /// Test the property 'Access'
        /// </summary>
        [Test]
        public void AccessTest()
        {
            // TODO unit test for the property 'Access'
        }
        /// <summary>
        /// Test the property 'BackupRule'
        /// </summary>
        [Test]
        public void BackupRuleTest()
        {
            // TODO unit test for the property 'BackupRule'
        }
        /// <summary>
        /// Test the property 'Backups'
        /// </summary>
        [Test]
        public void BackupsTest()
        {
            // TODO unit test for the property 'Backups'
        }
        /// <summary>
        /// Test the property 'License'
        /// </summary>
        [Test]
        public void LicenseTest()
        {
            // TODO unit test for the property 'License'
        }
        /// <summary>
        /// Test the property 'Servers'
        /// </summary>
        [Test]
        public void ServersTest()
        {
            // TODO unit test for the property 'Servers'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Tier'
        /// </summary>
        [Test]
        public void TierTest()
        {
            // TODO unit test for the property 'Tier'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Test]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
        /// <summary>
        /// Test the property 'Zone'
        /// </summary>
        [Test]
        public void ZoneTest()
        {
            // TODO unit test for the property 'Zone'
        }

    }

}
