/* 
 * Upcloud api
 *
 * Upcloud api specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing StorageBackups
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StorageBackupsTests
    {
        // TODO uncomment below to declare an instance variable for StorageBackups
        //private StorageBackups instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StorageBackups
            //instance = new StorageBackups();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StorageBackups
        /// </summary>
        [Test]
        public void StorageBackupsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StorageBackups
            //Assert.IsInstanceOfType<StorageBackups> (instance, "variable 'instance' is a StorageBackups");
        }

        /// <summary>
        /// Test the property 'Backup'
        /// </summary>
        [Test]
        public void BackupTest()
        {
            // TODO unit test for the property 'Backup'
        }

    }

}
