/* 
 * Upcloud api
 *
 * Upcloud api specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing StorageDevice
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StorageDeviceTests
    {
        // TODO uncomment below to declare an instance variable for StorageDevice
        //private StorageDevice instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StorageDevice
            //instance = new StorageDevice();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StorageDevice
        /// </summary>
        [Test]
        public void StorageDeviceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StorageDevice
            //Assert.IsInstanceOfType<StorageDevice> (instance, "variable 'instance' is a StorageDevice");
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'PartOfPlan'
        /// </summary>
        [Test]
        public void PartOfPlanTest()
        {
            // TODO unit test for the property 'PartOfPlan'
        }
        /// <summary>
        /// Test the property 'Storage'
        /// </summary>
        [Test]
        public void StorageTest()
        {
            // TODO unit test for the property 'Storage'
        }
        /// <summary>
        /// Test the property 'StorageSize'
        /// </summary>
        [Test]
        public void StorageSizeTest()
        {
            // TODO unit test for the property 'StorageSize'
        }
        /// <summary>
        /// Test the property 'StorageTitle'
        /// </summary>
        [Test]
        public void StorageTitleTest()
        {
            // TODO unit test for the property 'StorageTitle'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
