/* 
 * Upcloud api
 *
 * Upcloud api specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SuccessStoragesResponseStorages
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SuccessStoragesResponseStoragesTests
    {
        // TODO uncomment below to declare an instance variable for SuccessStoragesResponseStorages
        //private SuccessStoragesResponseStorages instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SuccessStoragesResponseStorages
            //instance = new SuccessStoragesResponseStorages();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SuccessStoragesResponseStorages
        /// </summary>
        [Test]
        public void SuccessStoragesResponseStoragesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SuccessStoragesResponseStorages
            //Assert.IsInstanceOfType<SuccessStoragesResponseStorages> (instance, "variable 'instance' is a SuccessStoragesResponseStorages");
        }

        /// <summary>
        /// Test the property 'Storage'
        /// </summary>
        [Test]
        public void StorageTest()
        {
            // TODO unit test for the property 'Storage'
        }

    }

}
